state =
[
state: "Washington",
state: "California",
state: "Colorado",
state: "Oregon",
state: "Alaska",
 nil,
state: "Utah",
state: "Wisconsin",
state: "Oklahoma",
state: "New York",
state: "Texas",
state: "Montana",
state: "North Carolina",
state: "Alberta",
state: "British Columbia",
state: "Tennessee",
state: "Arizona",
state: "Illinois",
state: "All",
state: "Virginia",
state: "Massachusetts",
state: "Arkansas",
state: "Ontario",
state: "Minnesota",
state: "Kentucky",
state: "Kansas",
state: "South Carolina",
state: "Iowa",
state: "Pennsylvania",
state: "Quebec",
state: "Idaho",
state: "Maryland",
state: "Florida",
state: "Louisiana",
state: "Michigan",
state: "New Mexico",
state: "Rhode Island",
state: "Ohio",
state: "Hawaii",
state: "West Virginia",
state: "Wyoming",
state: "Indiana",
state: "Nebraska"]

cities  =
 [
city: "Chelan",
city: "Bishop",
city: "Durango",
city: nil,
city: "Bandon",
city: "Delta Junction",
city: "Park City",
city: "Mexican Hat",
city: "Plymouth",
city: "Keystone",
city: "Nottinghamshire",
city: "Heavener",
city: "Cordova",
city: "Crested Butte",
city: "Waynoka",
city: "Akron",
city: "Bellingham",
city: "Twisp",
city: "Georgetown",
city: "Wise River",
city: "Brevard",
city: "Heber Springs",
city: "Wellington",
city: "Black Diamond",
city: "Lawrence",
city: "West Glacier",
city: "Santa Cruz",
city: "Scotch Creek",
city: "Sparta",
city: "Bergschenhoek",
city: "Morrisville",
city: "Alpine",
city: "Raleigh",
city: "Tongass/sitka",
city: "Albany",
city: "Pueblo",
city: "Bend",
city: "Shelbyville",
city: "Pulaski",
city: "Cairo",
city: "Buchanan",
city: "Randle",
city: "Seattle",
city: "Fall Creek Falls",
city: "Weymouth",
city: "Rome",
city: "Little Rock",
city: "Marten River",
city: "Minneapolis",
city: "Austin",
city: "Mammoth Cave",
city: "West Yellowstone",
city: "Wakefield",
city: "Spanish Forks",
city: "Blenheim",
city: "Oakland",
city: "Whitmire",
city: "Chantilly",
city: "Vernon",
city: "Waterloo and Hudson",
city: "Hookstown",
city: "Montreal",
city: "Istanbul",
city: "Stanley",
city: "Wheaton",
city: "Gainesville",
city: "Bastrop",
city: "Fanning Springs",
city: "Petoskey",
city: "Las Cruces",
city: "Cartago",
city: "East Providence",
city: "San Juan Capistrano",
city: "Berlin Center",
city: "Hana",
city: "Cle Elum",
city: "Bridgeport",
city: "Kingston",
city: "Ward",
city: "Safford",
city: "Lewisburg",
city: "Port Townsend",
city: "Arminto",
city: "Innisfail",
city: "Woodland Park",
city: "Raquette Lake",
city: "Whitefish",
city: "Bear Mountain",
city: "Yreka",
city: "New Liberty",
city: "Big Bear Lake",
city: "Fountain City",
city: "Glacier Ranger District",
city: "Enders"]


activity_type_name
activity_type: "snow sports"
activity_type: "hiking"
activity_type: "camping"
activity_type: "mountain biking"
activity_type: "caving"
